makeCacheMatrix <- function(x = matrix()) {
      
            inver_x <- NULL
            set <- function(y) {
                  x <<- y
                  inver_x <<- NULL
      }
      get <- function() x
      set_inver <- function(inverse) inver_x <<- inverse
      get_inver <- function() inver_x
     
      list(set = set,
           get = get,
           set_inver = set_inver ,
           get_inver = get_inver)
      
}


cacheSolve <- function(x, ...) {
      inver_x <- x$get_iver()
      if(!is.null(inver_x)) {
            message("Getting cached data.")
            return(inver_x)
      }
      data <- x$get()
      inver_x <- solve(data)
      x$set_inver(inver_x)
      inver_x
}
